// The image manifest must match what is actually on disk.
//
// Run: node test/manifest.mjs
//
// public/assets/images.json is how the dashboard knows a photo exists — a Worker
// cannot list a directory. The manifest is generated by `npm run images` and
// committed, which means it can go stale: push a photo, forget to regenerate,
// and the photo is invisible in the dashboard with no error anywhere.
//
// This test is the thing that catches that. It is the whole reason the
// build-time approach is safe to use.

import { readFileSync, existsSync, readdirSync } from "node:fs";
import { scanImages, buildManifest } from "../scripts/build-image-manifest.mjs";
import { suggestName } from "../src/admin.js";

let pass = 0, fail = 0;
const ok = (name, cond, detail = "") => {
  if (cond) { pass++; console.log(`  ok   ${name}`); }
  else { fail++; console.log(`  FAIL ${name}${detail ? " — " + detail : ""}`); }
};
const section = (s) => console.log(`\n${s}`);

const MANIFEST = "public/assets/images.json";

section("the committed manifest matches the images on disk");
{
  ok("images.json exists", existsSync(MANIFEST),
     "run `npm run images` and commit the result");

  if (existsSync(MANIFEST)) {
    const committed = JSON.parse(readFileSync(MANIFEST, "utf8"));
    const actual = buildManifest();

    ok("count matches", committed.count === actual.count,
       `manifest says ${committed.count}, disk has ${actual.count}`);

    const inManifest = new Set(committed.images.map((i) => i.file));
    const onDisk = new Set(actual.images.map((i) => i.file));

    const missing = [...onDisk].filter((f) => !inManifest.has(f));
    const stale = [...inManifest].filter((f) => !onDisk.has(f));

    // This is the failure that matters: a photo was pushed without regenerating,
    // so the dashboard will never offer to list it.
    ok("every image on disk is in the manifest", missing.length === 0,
       missing.length ? `run \`npm run images\` — missing: ${missing.slice(0, 5).join(", ")}` : "");
    ok("the manifest lists no deleted images", stale.length === 0,
       stale.length ? `stale: ${stale.slice(0, 5).join(", ")}` : "");

    // Sizes too — a re-exported photo at the same filename is a real change and
    // the dashboard shows the size.
    const bySize = new Map(actual.images.map((i) => [i.file, i.bytes]));
    const wrongSize = committed.images.filter((i) => bySize.has(i.file) && bySize.get(i.file) !== i.bytes);
    ok("recorded sizes are current", wrongSize.length === 0,
       wrongSize.length ? `${wrongSize.length} changed, e.g. ${wrongSize[0].file}` : "");
  }
}

section("the generator only picks up real images");
{
  const files = readdirSync("public/assets/images");
  const scanned = scanImages().map((i) => i.file);

  const nonImages = files.filter((f) => !/\.(jpe?g|png|webp|avif|gif)$/i.test(f));
  ok("non-image files are skipped", nonImages.every((f) => !scanned.includes(f)),
     nonImages.length ? `found: ${nonImages.join(", ")}` : "none present to skip");

  ok("every scanned file is an image",
     scanned.every((f) => /\.(jpe?g|png|webp|avif|gif)$/i.test(f)));
  ok("newest first", (() => {
    const s = scanImages();
    for (let i = 1; i < s.length; i++) if (s[i - 1].mtime < s[i].mtime) return false;
    return true;
  })());
  ok("no duplicates", new Set(scanned).size === scanned.length);
}

// ── suggestName ───────────────────────────────────────────────────
//
// The name pre-filled in the listing form. Getting this wrong is not dangerous,
// but a bad guess is worse than none: it invites listing a product called
// "Img20260403160453".
section("suggested names");
{
  const cases = [
    ["IMG20260725_kingfisher.jpg", "Kingfisher"],
    ["IMG20260521_temple_gopuram_two_tone.jpg", "Temple Gopuram Two Tone"],
    ["poster_wall_staircase_v1.jpg", "Poster Wall Staircase"],
    ["my-cool-dragon.png", "My Cool Dragon"],
    ["IMG20260403160453.jpg", ""],
    ["IMG20260413121025.jpg", ""],
    ["", ""],
  ];
  for (const [file, expect] of cases) {
    ok(`${file || "(empty)"} → ${JSON.stringify(expect)}`,
       suggestName(file) === expect, JSON.stringify(suggestName(file)));
  }
  ok("a camera-default name yields nothing, not a fake word",
     suggestName("IMG20260403160453.jpg") === "",
     "an invented name would be listed verbatim on the shop");
}

section("every listed product points at a real file");
{
  // The catalogue is seeded from migrations; if one references a photo that is
  // not in the repo, the shop renders a broken image and nothing else complains.
  // Match the path itself, on non-comment lines only.
  //
  // Two earlier attempts were wrong in instructive ways: scanning raw text
  // matched `-- assets/images/....jpg` in a schema comment (documentation, not a
  // reference), and matching quoted SQL values spanned whole blocks, because
  // apostrophes elsewhere in the file broke the quote pairing. The filename is
  // the thing being checked, so match that.
  const referenced = [...new Set(
    readdirSync("migrations")
      .flatMap((f) => readFileSync("migrations/" + f, "utf8").split("\n"))
      .filter((l) => !l.trim().startsWith("--"))
      .flatMap((l) => [...l.matchAll(/assets\/images\/([A-Za-z0-9_\-]+\.[a-z0-9]+)/gi)])
      .map((m) => m[1]),
  )];
  const onDisk = new Set(readdirSync("public/assets/images"));
  const broken = referenced.filter((f) => !onDisk.has(f));
  ok(`all ${referenced.length} referenced photos exist`, broken.length === 0,
     broken.slice(0, 5).join(", "));
}

console.log(`\n  manifest: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
