// Owner-only endpoints. Every handler here assumes the caller has ALREADY been
// authenticated by the positional gate in index.js — these functions never
// check auth themselves, so the gate must stay above them in the router.

import { json, bad, uid, now, sendEmail, statusLabel } from "./lib.js";
import { refundPayment, paymentsConfigured } from "./razorpay.js";
import { orderShippedEmail, orderInProductionEmail, orderDeliveredEmail } from "./emails.js";
import { checkAgentEntries, checkDescribeEntries } from "./agent.js";

const MAXLEN = { name: 120, slug: 80, desc: 2000, image: 300, images: 2000, category: 40, note: 500,
  courier: 60, tracking: 80, personalise: 80 };
const clip = (v, n) => String(v ?? "").trim().slice(0, n);

// Prices arrive from a form. Reject anything that isn't a whole number of
// paise: a float would round unpredictably at checkout, and a negative price
// would let a cart total go down as items are added.
function parsePaise(v) {
  if (v === undefined || v === null || v === "") return null;
  const n = typeof v === "number" ? v : Number(String(v).trim());
  if (!Number.isFinite(n) || !Number.isInteger(n) || n < 0) return null;
  return n;
}

const slugify = (s) =>
  clip(s, MAXLEN.slug).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

// ── products ──────────────────────────────────────────────────────
// Unlike the public /api/products, this returns hidden rows too — that's the
// point of the dashboard.
// Same ordering as the shop — see the note on listProducts() in src/shop.js for
// why each key is there. Kept identical so the dashboard shows what a customer
// sees rather than a second opinion about it.
export async function listProducts(env) {
  const { results } = await env.DB.prepare(
    `SELECT id, slug, name, description, price_paise, image, images, category,
            visible, sort, personalise_label, personalise_required, pinned,
            created_at, updated_at
       FROM products
        ORDER BY pinned DESC, created_at DESC, (sort = 0), sort ASC, name ASC`
  ).all();
  return json({ products: results || [] });
}

// ── the image manifest ────────────────────────────────────────────
//
// A Worker cannot list a directory: the [assets] binding serves files but has no
// index. public/assets/images.json is generated by scripts/build-image-manifest.mjs
// and committed with the photos, so it is the only thing that knows what exists.
//
// Fetched through the ASSETS binding rather than imported, so adding a photo does
// not require a code change — push the image and its manifest entry, and the
// dashboard sees it on the next request.
async function readManifest(env) {
  try {
    const res = await env.ASSETS.fetch(new Request("https://assets.local/assets/images.json"));
    if (!res.ok) {
      console.error("image manifest fetch failed", res.status);
      return null;
    }
    const data = await res.json();
    return Array.isArray(data?.images) ? data : null;
  } catch (e) {
    console.error("image manifest unreadable", e?.message || e);
    return null;
  }
}

// Every image path the catalogue already uses — the primary `image` and each
// entry of the comma-separated `images` column.
//
// Both matter: a photo used only as a secondary view of an existing product is
// NOT unlisted, and offering to list it again would create a duplicate product
// from a photo of one that already exists.
async function usedImagePaths(env) {
  const { results } = await env.DB.prepare(
    `SELECT image, images FROM products`
  ).all();

  const used = new Set();
  for (const row of results || []) {
    const add = (p) => {
      const f = String(p || "").trim();
      if (f) used.add(f.replace(/^.*\//, ""));   // compare by filename
    };
    add(row.image);
    for (const extra of String(row.images || "").split(",")) add(extra);
  }
  return used;
}

// GET /api/admin/products/unlisted
//
// Photos in the repo that no product row points at — i.e. the ones Aswin just
// pushed and has not priced yet.
export async function unlistedImages(env) {
  const manifest = await readManifest(env);
  if (!manifest) {
    return json({
      images: [], manifest_missing: true,
      error: "Could not read assets/images.json. Run `npm run images` and push it.",
    });
  }

  const used = await usedImagePaths(env);
  const unlisted = manifest.images
    .filter((i) => !used.has(i.file))
    .map((i) => ({
      file: i.file,
      path: `assets/images/${i.file}`,
      bytes: i.bytes,
      // A name guessed from the filename, so listing is usually one field.
      // IMG20260725_kingfisher.jpg -> "Kingfisher". A camera-default name like
      // IMG20260403160453.jpg has nothing to work with and yields "", which the
      // dashboard shows as an empty field rather than an invented word.
      suggested_name: suggestName(i.file),
    }));

  return json({
    images: unlisted,
    total_images: manifest.images.length,
    listed: used.size,
    generated_at: manifest.generated_at || null,
  });
}

// "IMG20260725_kingfisher.jpg" -> "Kingfisher"
// "poster_wall_staircase_v1.jpg" -> "Poster Wall Staircase"
// "IMG20260403160453.jpg" -> "" (nothing but a camera timestamp)
export function suggestName(file) {
  const stem = String(file || "").replace(/\.[a-z0-9]+$/i, "");
  const words = stem
    .replace(/^IMG[-_]?\d+[-_]?/i, "")     // camera prefix + timestamp
    .replace(/[-_]v\d+$/i, "")             // version suffix
    .split(/[-_\s]+/)
    .filter((w) => w && !/^\d+$/.test(w)); // drop pure-number fragments
  if (!words.length) return "";
  return words
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

export async function createProduct(env, body) {
  const name = clip(body?.name, MAXLEN.name);
  const price = parsePaise(body?.price_paise);
  const image = clip(body?.image, MAXLEN.image);

  if (name.length < 2) return bad("Name is required.");
  if (price === null) return bad("Price must be a whole number of paise (e.g. 34900 for ₹349).");
  if (!image) return bad("Image path is required.");

  // The image must be a file that actually exists in the repo.
  //
  // Without this the field is an arbitrary client-controlled string: a product
  // could point at an external URL (so the shop renders a stranger's image and
  // leaks referrer traffic), at a path traversal, or at a file that simply is
  // not there — producing a listing with a broken image that looks live.
  //
  // Same discipline as priceCart: the client NAMES a thing, the server decides
  // whether it is real. Checked against the manifest, which is the only list of
  // what exists.
  const manifest = await readManifest(env);
  if (!manifest) return bad("Image manifest unavailable — run `npm run images` and deploy.", 503);

  const known = new Set(manifest.images.map((i) => i.file));
  const named = image.replace(/^.*\//, "");
  if (!known.has(named) || /^https?:|^\/\/|\.\./i.test(image)) {
    return bad("That image is not in assets/images. Push the photo, run `npm run images`, and try again.");
  }
  // Store the canonical path regardless of what was sent, so a valid filename
  // with a strange prefix cannot end up in the database verbatim.
  const imagePath = `assets/images/${named}`;

  // Secondary views get the same treatment — they are rendered on the product
  // page exactly like the primary image.
  const extraRaw = clip(body?.images, MAXLEN.images);
  const extras = [];
  for (const part of extraRaw.split(",")) {
    const f = part.trim().replace(/^.*\//, "");
    if (!f) continue;
    if (!known.has(f)) return bad(`Extra image "${f}" is not in assets/images.`);
    extras.push(`assets/images/${f}`);
  }

  const slug = slugify(body?.slug || name);
  if (!slug) return bad("Could not derive a slug from that name.");

  const dup = await env.DB.prepare(`SELECT id FROM products WHERE slug = ?`).bind(slug).first();
  if (dup) return bad("A product with that slug already exists.", 409);

  const id = uid();
  const ts = now();
  await env.DB.prepare(
    `INSERT INTO products (id, slug, name, description, price_paise, image, images,
       category, visible, sort, created_at, updated_at)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`
  ).bind(
    id, slug, name, clip(body?.description, MAXLEN.desc), price, imagePath,
    extras.join(","), clip(body?.category, MAXLEN.category),
    // Default VISIBLE. A product listed from the dashboard is one Aswin has just
    // priced and wants to sell; creating it hidden means it silently does not
    // appear and the next step is wondering why.
    body?.visible === false ? 0 : 1,
    parsePaise(body?.sort) ?? 0, ts, ts,
  ).run();

  return json({ ok: true, id, slug, image: imagePath }, 201);
}

// ── batch operations on unlisted photos ───────────────────────────
//
// Both of these take a list of FILENAMES from the unlisted panel and write one
// product row each, in a single transaction.
//
// The transaction is the point. Looping over createProduct() from the browser
// would fail partway on the first bad filename or duplicate slug, leaving some
// photos listed and some not — and no obvious way to tell which. `env.DB.batch()`
// is one D1 transaction: it all lands or none of it does.

// Validate a list of ENTRIES against the manifest and plan a row for each.
//
// An entry is { file, price, category, visible, name?, description? }. Values are
// per-entry rather than shared across the batch: the unlisted panel has always had
// a Price box on every row, and it now submits them together, so ten photos can go
// live at ten different prices in one transaction.
//
// Shared with hide, which maps its filenames to entries at price 0 — the checks are
// identical and only the contents of the rows differ, which is the reason this is
// one function and not two.
async function planRowsFor(env, entries) {
  if (!Array.isArray(entries) || entries.length === 0) return { error: "No photos selected." };
  if (entries.length > 100) return { error: "Too many photos in one request (max 100)." };

  const manifest = await readManifest(env);
  if (!manifest) return { error: "Image manifest unavailable — run `npm run images` and deploy.", status: 503 };
  const known = new Set(manifest.images.map((i) => i.file));

  // Slugs must be unique across the WHOLE table, so existing rows are pulled in
  // before deciding. Cheap: this is an admin path and the catalogue is ~60 rows.
  const { results: existing } = await env.DB.prepare(`SELECT slug, image FROM products`).all();
  const takenSlugs = new Set((existing || []).map((r) => r.slug));
  const alreadyListed = new Set((existing || []).map((r) => String(r.image || "").replace(/^.*\//, "")));

  const seen = new Set();
  const rows = [];

  for (const entry of entries) {
    const raw = entry?.file;
    const file = String(raw || "").trim().replace(/^.*\//, "");
    if (!file) return { error: "An entry in the selection is empty." };

    // Same guard as createProduct, for the same reason: these are
    // client-supplied strings, so an external URL or a traversal must not become
    // a product's image. See the note there.
    if (!known.has(file) || /^https?:|^\/\/|\.\./i.test(String(raw))) {
      return { error: `"${file}" is not in assets/images. Push the photo, run \`npm run images\`, and try again.` };
    }
    if (seen.has(file)) return { error: `"${file}" is selected twice.` };
    seen.add(file);
    if (alreadyListed.has(file)) return { error: `"${file}" is already a product.` };

    // The row's own name if it has one. A camera-default filename yields nothing to
    // name a product after, and blocking the whole batch for that would be worse
    // than a placeholder Aswin can edit.
    const name = clip(entry?.name, MAXLEN.name) || suggestName(file) || "Custom piece";

    // De-duplicate the slug against existing rows AND against earlier entries in
    // this same batch.
    //
    // This is not hypothetical: poster_wall_staircase.jpg and
    // poster_wall_staircase_v2.jpg both slugify to "poster-wall-staircase", so
    // selecting both — which the "select all" button makes easy — would collide.
    let slug = slugify(name) || "item";
    if (takenSlugs.has(slug)) {
      let n = 2;
      while (takenSlugs.has(`${slug}-${n}`)) n++;
      slug = `${slug}-${n}`;
    }
    takenSlugs.add(slug);

    rows.push({
      id: uid(),
      slug,
      name,
      image: `assets/images/${file}`,
      price: entry.price,
      category: clip(entry?.category, MAXLEN.category),
      visible: entry.visible,
      description: clip(entry?.description, MAXLEN.desc),
    });
  }

  return { rows };
}

// POST /api/admin/products/batch — list several photos, each at its own price.
//
// Takes `items: [{ file, price_paise, name?, category?, description? }]`, mirroring
// bulkUpdateProducts() above: validate and plan everything first, write once. Any bad
// row rejects the whole batch, which is the same promise the transaction makes —
// listing nine of ten photos and leaving no clear record of which failed is worse
// than listing none.
export async function batchCreateProducts(env, body, actor = "owner", ctx = null) {
  const items = body?.items;

  // A dashboard tab loaded before this shipped posts the old shape: a list of
  // filenames plus one shared price. Say so, rather than falling through to "No
  // photos selected." and leaving Aswin wondering why the button stopped working.
  if (!Array.isArray(items) && Array.isArray(body?.images)) {
    return bad("This dashboard page is out of date — reload it and try again.", 409);
  }
  if (!Array.isArray(items) || items.length === 0) return bad("No photos selected.");

  const entries = [];
  for (const it of items) {
    const file = String(it?.file || "").trim().replace(/^.*\//, "") || "a photo";
    const price = parsePaise(it?.price_paise);
    // Naming the file matters: in a batch of twenty, "enter a price" without saying
    // which row is a hunt.
    if (price === null || price < 1) {
      return bad(`Enter a price in rupees for "${file}".`);
    }
    entries.push({
      file: it?.file,
      price,
      category: it?.category,
      name: it?.name,
      description: it?.description,
      visible: it?.visible === false ? 0 : 1,
    });
  }

  // Agent-authored batches get extra rails, checked BEFORE planRowsFor so a
  // rejected batch writes nothing. planRowsFor already guarantees new-items-only
  // for every caller; this is the separate question of what values a token that
  // publishes straight to the live shop may set.
  if (actor === "agent") {
    const problem = checkAgentEntries(entries);
    if (problem) return bad(problem, 400);
  }

  const planned = await planRowsFor(env, entries);
  if (planned.error) return bad(planned.error, planned.status || 400);

  await writeProductRows(env, planned.rows);

  // Tell Aswin what just went live. This is the only compensating control for
  // "live immediately" — the agent's price reaches customers with no review, so the
  // least this can do is make sure he finds out the same minute rather than the next
  // time he happens to open the dashboard.
  //
  // waitUntil, not await: the write is already committed and the agent's response
  // should not wait on Resend. Guarded because ctx is absent in the unit tests and
  // on the owner path, where it is not wanted anyway.
  if (actor === "agent" && ctx?.waitUntil) {
    ctx.waitUntil(notifyAgentListings(env, planned.rows).catch((e) =>
      console.error("agent listing notification failed", e?.message || e)));
  }
  console.log(`${actor} listed ${planned.rows.length} product(s): ` +
    planned.rows.map((r) => `${r.slug}@${r.price}`).join(" "));

  return json({
    ok: true,
    created: planned.rows.length,
    products: planned.rows.map((r) => ({ id: r.id, slug: r.slug, name: r.name, image: r.image })),
  }, 201);
}

// Plain and scannable on a phone: what went live, at what price, and the link to
// change it. No HTML cleverness — this is an alert, and the only thing that matters
// is that a wrong number is obvious at a glance.
// Built as a pure function and EXPORTED so it can be tested, which is the whole
// point of it not being inline any more.
//
// It shipped reading r.price_paise. planRowsFor() names that field `price` — the
// paise suffix appears on the database column and on the API payload, not on the
// planned row — so the arithmetic was undefined/100 and Aswin's notification for a
// real ₹1,999 listing said "Marvel Wall Art — ₹NaN". The product itself was written
// correctly; only the mail that told him about it was wrong, which is the worst shape
// for a bug like this because the thing reporting the state is the broken part.
//
// The price is read once, here, and asserted on in test/admin.mjs.
export function agentListingEmail(rows, site) {
  const rupees = (r) => {
    // Explicit, because this is exactly where the bug lived. A row that somehow has
    // no numeric price must say so rather than render as NaN and look like a
    // formatting quirk.
    const paise = r.price;
    return Number.isFinite(paise) ? `₹${(paise / 100).toFixed(0)}` : "price missing";
  };
  const n = rows.length;
  return {
    subject: `${n} new product${n === 1 ? "" : "s"} listed by the agent`,
    text: `These are LIVE in the shop now.\n\n` +
      rows.map((r) => `${r.name} — ${rupees(r)}  ${site}/p/${r.slug}`).join("\n") +
      `\n\nIf a price is wrong, change it at ${site}/shop.html — the listing agent ` +
      `cannot edit an existing product, so it will not overwrite your correction.`,
    html: `<p>These are <strong>live in the shop now</strong>.</p><ul>` +
      rows.map((r) => `<li><a href="${site}/p/${r.slug}">${escapeHtml(r.name)}</a> — ` +
        `<strong>${rupees(r)}</strong></li>`).join("") +
      `</ul><p>If a price is wrong, change it in the dashboard. The listing agent ` +
      `cannot edit an existing product, so it will not overwrite your correction.</p>`,
  };
}

async function notifyAgentListings(env, rows) {
  const to = String(env.OWNER_EMAIL || "").split(",")[0].trim();
  if (!to) return;
  const site = env.SITE_URL || "https://3d-prints.aswincloud.com";
  await sendEmail(env, { to, ...agentListingEmail(rows, site) });
}

const escapeHtml = (s) => String(s).replace(/[&<>"]/g,
  (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

// POST /api/admin/products/describe — fill in a description that is MISSING.
//
// The only route the listing agent has that writes to a row it did not create, which
// makes it the one worth being suspicious of. Two things keep it honest, and the order
// matters:
//
//   1. The UPDATE carries `AND (description IS NULL OR TRIM(description) = '')`.
//      This is the actual guarantee. Overwriting an existing description is not
//      something this statement is able to do, whatever reaches it — a bug in the
//      validation below, a caller that skips it, a future refactor that reorders it.
//      The same reasoning as writeProductRows() being INSERT-only: put the limit in
//      the SQL, not in the JavaScript that hopes to run first.
//
//   2. A validate-then-write pass so a request that WOULD have been a no-op gets a
//      readable 409 naming the slug, instead of a silent "ok, 0 changed" that an
//      agent would have no way to interpret.
//
// price_paise, name, slug and visible are absent from the statement entirely. Money
// and shelf presence are not editable through this route at any privilege level.
export async function describeProducts(env, body, actor = "owner", ctx = null) {
  const items = body?.items;
  if (!Array.isArray(items) || items.length === 0) return bad("No products given.");

  const entries = [];
  for (const it of items) {
    const slug = clip(it?.slug, MAXLEN.slug);
    if (!slug) return bad("An entry has no slug.");
    entries.push({
      slug,
      description: clip(it?.description, MAXLEN.desc),
      // null means "leave the category alone", which is different from "" — the
      // COALESCE below depends on the distinction.
      category: it?.category == null || it.category === ""
        ? null : clip(it.category, MAXLEN.category),
    });
  }

  if (actor === "agent") {
    const problem = checkDescribeEntries(entries);
    if (problem) return bad(problem, 400);
  }

  // Pass one: read, decide, write nothing.
  const { results } = await env.DB.prepare(
    `SELECT slug, description FROM products`).all();
  const bySlug = new Map((results || []).map((r) => [r.slug, r]));
  const seen = new Set();
  for (const e of entries) {
    if (seen.has(e.slug)) return bad(`"${e.slug}" appears twice in this request.`);
    seen.add(e.slug);
    const row = bySlug.get(e.slug);
    if (!row) return bad(`"${e.slug}" is not a product.`, 404);
    if (String(row.description || "").trim()) {
      return bad(
        `"${e.slug}" already has a description. This route only fills in empty ones — ` +
        `edit it from the dashboard instead.`, 409);
    }
  }

  // Pass two: one transaction.
  const stmt = env.DB.prepare(
    `UPDATE products
        SET description = ?, category = COALESCE(?, category), updated_at = ?
      WHERE slug = ?
        AND (description IS NULL OR TRIM(description) = '')`);
  const ts = now();
  const res = await env.DB.batch(
    entries.map((e) => stmt.bind(e.description, e.category, ts, e.slug)));

  // Report what the DATABASE did, not what was asked for. If the WHERE clause
  // rejected a row — someone described it between the two passes — that has to show
  // up here rather than being reported as success.
  const changed = res.reduce((n, r) => n + (r?.meta?.changes || 0), 0);
  console.log(`${actor} described ${changed}/${entries.length}: ` +
    entries.map((e) => e.slug).join(" "));

  if (actor === "agent" && ctx?.waitUntil && changed) {
    ctx.waitUntil(notifyAgentDescriptions(env, entries.slice(0, changed))
      .catch((e) => console.error("describe notification failed", e?.message || e)));
  }

  return json({
    ok: true,
    described: changed,
    requested: entries.length,
    slugs: entries.map((e) => e.slug),
    ...(changed < entries.length
      ? { note: "Some rows were not changed — they gained a description between the check and the write." }
      : {}),
  });
}

async function notifyAgentDescriptions(env, entries) {
  const to = String(env.OWNER_EMAIL || "").split(",")[0].trim();
  if (!to) return;
  const site = env.SITE_URL || "https://3d-prints.aswincloud.com";
  await sendEmail(env, {
    to,
    subject: `${entries.length} product description${entries.length === 1 ? "" : "s"} written by the agent`,
    text: `These products had no description and now do. Prices are unchanged — this ` +
          `route cannot touch them.\n\n` +
          entries.map((e) => `${e.slug}\n${site}/p/${e.slug}\n${e.description}\n`).join("\n"),
    html: `<p>These products had no description and now do. Prices are unchanged — ` +
          `this route cannot touch them.</p>` +
          entries.map((e) =>
            `<p><a href="${site}/p/${e.slug}">${escapeHtml(e.slug)}</a><br>` +
            `<span style="color:#555">${escapeHtml(e.description)}</span></p>`).join(""),
  });
}

// POST /api/admin/products/hide — take photos out of the shop without deleting
// the files.
//
// The posters are Instagram creatives: they belong in the repo (they are used on
// Instagram) but not in the storefront, where they read as products that tell
// customers to DM instead of buying.
//
// Implemented as a HIDDEN PRODUCT ROW rather than a separate ignore-list table.
// listProducts() already excludes images belonging to hidden products from the
// auto-listing (see the note in src/shop.js), so this reuses a path that exists
// and is tested — and the result is visible and reversible in the products list
// rather than buried in a second place where "why is this not showing?" can be
// answered.
//
// Note it does NOT go through createProduct(), which requires a price: hiding a
// poster would otherwise mean inventing a price for something never meant to be
// sold.
export async function hideImages(env, body) {
  const images = body?.images;
  if (!Array.isArray(images) || images.length === 0) return bad("No photos selected.");

  // Hide still takes a plain list of filenames — there is nothing per-row to say
  // about a photo that will never be sold. Mapped to entries so it keeps sharing
  // planRowsFor's checks rather than growing a parallel copy of them.
  const planned = await planRowsFor(env, images.map((file) => ({
    file,
    price: 0,        // never sellable; priceCart refuses price_paise = 0 anyway
    category: "",
    visible: 0,
    description: "",
  })));
  if (planned.error) return bad(planned.error, planned.status || 400);

  await writeProductRows(env, planned.rows);
  return json({
    ok: true,
    hidden: planned.rows.length,
    images: planned.rows.map((r) => r.image),
  }, 201);
}

// One transaction for the whole set.
function writeProductRows(env, rows) {
  const ts = now();
  const stmt = env.DB.prepare(
    `INSERT INTO products (id, slug, name, description, price_paise, image, images,
       category, visible, sort, created_at, updated_at)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`
  );
  // r.description, not "". The single-photo path carries a description through
  // createProduct() and this one used to drop it on the floor — invisible while the
  // batch form had no description box, and silent data loss the moment it submits the
  // one each row has always had.
  return env.DB.batch(rows.map((r) => stmt.bind(
    r.id, r.slug, r.name, r.description || "", r.price, r.image, "", r.category,
    r.visible, 0, ts, ts,
  )));
}

// PATCH semantics: only the fields present in the body are touched, so the
// dashboard can send just a price or just a visibility toggle.
export async function updateProduct(env, id, body) {
  const existing = await env.DB.prepare(`SELECT id FROM products WHERE id = ?`).bind(id).first();
  if (!existing) return bad("Product not found.", 404);

  const sets = [];
  const args = [];
  const put = (col, val) => { sets.push(`${col} = ?`); args.push(val); };

  if ("name" in body) {
    const name = clip(body.name, MAXLEN.name);
    if (name.length < 2) return bad("Name is too short.");
    put("name", name);
  }
  if ("price_paise" in body) {
    const price = parsePaise(body.price_paise);
    if (price === null) return bad("Price must be a whole number of paise.");
    put("price_paise", price);
  }
  if ("description" in body) put("description", clip(body.description, MAXLEN.desc));
  // An empty label means "this product does not ask" — that is the off switch,
  // so it must be settable back to empty, not just to a new string.
  if ("personalise_label" in body) {
    put("personalise_label", clip(body.personalise_label, MAXLEN.personalise));
  }
  if ("personalise_required" in body) {
    put("personalise_required", body.personalise_required ? 1 : 0);
  }
  // Same check as createProduct: the client names a file, the manifest decides
  // whether it exists. This path used to accept any string — an external URL,
  // a traversal, a typo — and the shop would render whatever it was told.
  if ("image" in body || "images" in body) {
    const manifest = await readManifest(env);
    if (!manifest) return bad("Image manifest unavailable — run `npm run images` and deploy.", 503);
    const known = new Set(manifest.images.map((i) => i.file));

    if ("image" in body) {
      const image = clip(body.image, MAXLEN.image);
      if (!image) return bad("Image path cannot be empty.");
      const named = image.replace(/^.*\//, "");
      if (!known.has(named) || /^https?:|^\/\/|\.\./i.test(image)) {
        return bad("That image is not in assets/images. Push the photo, run `npm run images`, and try again.");
      }
      put("image", `assets/images/${named}`);
    }
    if ("images" in body) {
      const extras = [];
      for (const part of clip(body.images, MAXLEN.images).split(",")) {
        const f = part.trim().replace(/^.*\//, "");
        if (!f) continue;
        if (!known.has(f)) return bad(`Extra image "${f}" is not in assets/images.`);
        extras.push(`assets/images/${f}`);
      }
      put("images", extras.join(","));
    }
  }
  if ("category" in body) put("category", clip(body.category, MAXLEN.category));
  if ("visible" in body) put("visible", body.visible ? 1 : 0);
  // Leads the catalogue. A toggle, so coerced rather than validated — there is
  // no value a caller could send that means anything other than on or off.
  if ("pinned" in body) put("pinned", body.pinned ? 1 : 0);
  if ("sort" in body) {
    const sort = parsePaise(body.sort);
    if (sort === null) return bad("Sort must be a non-negative integer.");
    put("sort", sort);
  }
  if ("slug" in body) {
    const slug = slugify(body.slug);
    if (!slug) return bad("Slug cannot be empty.");
    const dup = await env.DB.prepare(
      `SELECT id FROM products WHERE slug = ? AND id != ?`
    ).bind(slug, id).first();
    if (dup) return bad("Another product already uses that slug.", 409);
    put("slug", slug);
  }

  if (!sets.length) return bad("Nothing to update.");

  put("updated_at", now());
  args.push(id);
  await env.DB.prepare(`UPDATE products SET ${sets.join(", ")} WHERE id = ?`).bind(...args).run();

  const row = await env.DB.prepare(
    `SELECT id, slug, name, description, price_paise, image, images, category,
            visible, sort, updated_at FROM products WHERE id = ?`
  ).bind(id).first();
  return json({ ok: true, product: row });
}

// ── bulk update ───────────────────────────────────────────────────
// PATCH /api/admin/products with
// { items: [{id, price_paise?, visible?, description?, personalise_label?,
//            personalise_required?, pinned?}] }.
//
// Exists because correcting the seeded placeholder prices meant 26 separate
// round trips through the single-row endpoint. Same validation as
// updateProduct().
//
// Price, visibility and description are settable in bulk — the three things a
// catalogue pass actually changes. Description was added last: it was already
// settable one row at a time through updateProduct(), so the dashboard could
// offer it per-row and not in "Save all changes", which would have meant an edit
// silently sitting outside the batch the bulk bar claims to be counting.
//
// This does NOT widen the listing agent. AGENT_ROUTES in agent.js is an
// exact-match allowlist that omits `PATCH /api/admin/products` precisely because
// it reaches every existing row; a field added here is a field the agent still
// cannot reach. test/admin.mjs asserts that rather than trusting this comment.
//
// ALL-OR-NOTHING on purpose: every row is validated before anything is written.
// A partial write is the worst outcome here — you'd have no idea which of 26
// prices took, and re-submitting would double-apply nothing but would still
// leave you guessing. One bad row rejects the batch and names it.
export async function bulkUpdateProducts(env, body) {
  const items = body?.items;
  if (!Array.isArray(items) || items.length === 0) {
    return bad("Nothing to update.");
  }
  if (items.length > 200) return bad("Too many products in one request.");

  // Pass 1: validate and resolve. Nothing is written in this pass.
  const seen = new Set();
  const planned = [];
  for (const it of items) {
    const id = clip(it?.id, 40);
    if (!id) return bad("An item is missing its id.");
    if (seen.has(id)) return bad("The same product appears twice in one request.");
    seen.add(id);

    const sets = [];
    const args = [];

    if ("price_paise" in (it || {})) {
      const price = parsePaise(it.price_paise);
      if (price === null) {
        return bad(`Price for one item isn't a whole number of paise (got ${JSON.stringify(it.price_paise)}).`);
      }
      sets.push("price_paise = ?");
      args.push(price);
    }
    if ("visible" in (it || {})) {
      sets.push("visible = ?");
      args.push(it.visible ? 1 : 0);
    }
    // Clipped, not rejected — same as updateProduct(). A description is prose
    // typed into a textarea; failing the whole batch because someone ran 40
    // characters over the limit would lose every other edit in it, and the
    // textarea already shows a counter.
    if ("description" in (it || {})) {
      sets.push("description = ?");
      args.push(clip(it.description, MAXLEN.desc));
    }
    if ("personalise_label" in (it || {})) {
      sets.push("personalise_label = ?");
      args.push(clip(it.personalise_label, MAXLEN.personalise));
    }
    if ("personalise_required" in (it || {})) {
      sets.push("personalise_required = ?");
      args.push(it.personalise_required ? 1 : 0);
    }
    if ("pinned" in (it || {})) {
      sets.push("pinned = ?");
      args.push(it.pinned ? 1 : 0);
    }
    if (!sets.length) return bad("An item has nothing to update.");

    planned.push({ id, sets, args });
  }

  // Confirm every id exists before touching anything — otherwise a typo'd id
  // would silently update nothing while reporting success.
  const ids = planned.map((p) => p.id);
  const ph = ids.map(() => "?").join(",");
  const { results } = await env.DB.prepare(
    `SELECT id FROM products WHERE id IN (${ph})`
  ).bind(...ids).all();
  const found = new Set((results || []).map((r) => r.id));
  const missing = ids.filter((i) => !found.has(i));
  if (missing.length) {
    return bad(`${missing.length} product(s) in this request no longer exist. Reload and try again.`, 409);
  }

  // Pass 2: write. batch() is a single D1 transaction, so a failure mid-way
  // rolls the whole thing back rather than leaving half the prices changed.
  const ts = now();
  const stmts = planned.map((p) => env.DB.prepare(
    `UPDATE products SET ${p.sets.join(", ")}, updated_at = ? WHERE id = ?`
  ).bind(...p.args, ts, p.id));

  await env.DB.batch(stmts);

  const { results: rows } = await env.DB.prepare(
    `SELECT id, slug, name, price_paise, visible FROM products WHERE id IN (${ph})`
  ).bind(...ids).all();

  return json({ ok: true, updated: planned.length, products: rows || [] });
}

// Deleting a product must never alter order history: order_items snapshots the
// name and price, and its product_id is nullable precisely so this can happen.
// It is NOT a cascade — the FK is on order_id, not product_id.
export async function deleteProduct(env, id) {
  const row = await env.DB.prepare(`SELECT id, name FROM products WHERE id = ?`).bind(id).first();
  if (!row) return bad("Product not found.", 404);

  const sold = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM order_items WHERE product_id = ?`
  ).bind(id).first();

  // Hiding is almost always what's wanted for something already sold: it keeps
  // the row available for reporting while removing it from the shop.
  if ((sold?.n || 0) > 0) {
    await env.DB.prepare(`UPDATE products SET visible = 0, updated_at = ? WHERE id = ?`)
      .bind(now(), id).run();
    return json({
      ok: true, hidden: true, orders: sold.n,
      message: `"${row.name}" appears in ${sold.n} order line(s), so it was hidden rather than deleted. Order history is preserved.`,
    });
  }

  await env.DB.prepare(`DELETE FROM products WHERE id = ?`).bind(id).run();
  return json({ ok: true, deleted: true });
}

// ── orders ────────────────────────────────────────────────────────
// The pipeline, plus the three outcomes that end it. Kept in this order so the
// dashboard's status filter reads like the journey.
const ORDER_STATUSES = [
  "pending", "paid", "in_production", "ready", "shipped", "delivered",
  "failed", "cancelled", "refunded",
];

// Where a refund is still possible. Widened with the production stages
// DELIBERATELY: money has changed hands from `paid` onwards, and a customer who
// asks for their money back while the print is on the bed must not be told
// `Cannot refund an order with status "in_production"`.
const REFUNDABLE = ["paid", "in_production", "ready", "shipped", "delivered"];

export async function listOrders(env, url) {
  const status = clip(url.searchParams.get("status"), 20);
  const limit = Math.min(200, Math.max(1, parseInt(url.searchParams.get("limit"), 10) || 100));

  const where = ORDER_STATUSES.includes(status) ? `WHERE status = ?` : "";
  const bindArgs = where ? [status, limit] : [limit];

  const { results: orders } = await env.DB.prepare(
    `SELECT id, receipt, rzp_order_id, rzp_payment_id, status, subtotal_paise,
            discount_paise, coupon_code, shipping_paise, total_paise, delivery,
            cust_name, cust_email, cust_phone, addr_line, addr_city, addr_state,
            addr_pin, notes, created_at, paid_at, production_at, ready_at,
            shipped_at, delivered_at, courier, tracking_id
       FROM orders ${where} ORDER BY created_at DESC LIMIT ?`
  ).bind(...bindArgs).all();

  const list = orders || [];

  // One query for all line items rather than N+1.
  let items = [];
  if (list.length) {
    const ph = list.map(() => "?").join(",");
    const r = await env.DB.prepare(
      `SELECT order_id, name, price_paise, qty, personalisation, pos FROM order_items
        WHERE order_id IN (${ph}) ORDER BY pos`
    ).bind(...list.map((o) => o.id)).all();
    items = r.results || [];
  }

  const byOrder = new Map();
  for (const it of items) {
    if (!byOrder.has(it.order_id)) byOrder.set(it.order_id, []);
    byOrder.get(it.order_id).push(it);
  }

  const { results: counts } = await env.DB.prepare(
    `SELECT status, COUNT(*) AS n, SUM(total_paise) AS total FROM orders GROUP BY status`
  ).all();

  return json({
    orders: list.map((o) => ({
      ...o,
      items: byOrder.get(o.id) || [],
      // Told to the dashboard rather than mirrored there. The transition table
      // and the refund rule live here and are re-checked here; a second copy in
      // the browser would be one more thing to keep in step, and drift would show
      // up as a button that 409s.
      status_label: statusLabel(o.status),
      next_stages: ALLOWED_TRANSITIONS[o.status] || [],
      can_refund: REFUNDABLE.includes(o.status) && Boolean(o.rzp_payment_id),
    })),
    counts: counts || [],
  });
}

// Status transitions are restricted. 'paid' is deliberately NOT settable here:
// it's written by the webhook from Razorpay's confirmation, and letting the
// dashboard set it by hand would mean an unpaid order could be marked paid.
const ALLOWED_TRANSITIONS = {
  pending: ["cancelled"],
  // Skipping forward stays legal. Something already on the shelf still ships in
  // ONE click, exactly as before these stages existed — adding stages must not
  // turn a one-click job into four.
  paid: ["in_production", "ready", "shipped", "cancelled"],
  in_production: ["ready", "shipped", "cancelled"],
  ready: ["shipped", "cancelled"],
  shipped: ["delivered", "cancelled"],
  // Terminal. A refund is still possible, but only through the refund action,
  // which is what actually moves the money.
  delivered: [],
  failed: ["cancelled"],
};

// The timestamp each stage stamps on arrival. Mirrors paid_at / shipped_at,
// which already worked this way.
const STAGE_STAMP = {
  in_production: "production_at",
  ready: "ready_at",
  shipped: "shipped_at",
  delivered: "delivered_at",
};

// Which stages email the customer, and what they say.
//
// `ready` is deliberately ABSENT: it advances the tracker and the dashboard and
// sends nothing. It is usually only hours before shipping, and two mails that
// close together read as padding rather than progress. Its absence from this
// table is the entire implementation of that decision.
const STAGE_EMAIL = {
  in_production: {
    subject: (o) => `We've started printing your order — ${o.receipt}`,
    html: (env, o) => orderInProductionEmail(env, o),
    text: (o) => `Good news — your order ${o.receipt} is on the printer now.\n`
      + `\nI'll email you again when it ships.\n\n— Aswin\nhttps://3d-prints.aswincloud.com\n`,
  },
  shipped: {
    subject: (o) => `Your order has shipped — ${o.receipt}`,
    html: (env, o) => orderShippedEmail(env, o, {
      courier: o.courier,
      tracking: o.tracking_id,
      trackingUrl: trackingUrlFor(o.courier, o.tracking_id),
    }),
    text: (o) => `Your order ${o.receipt} has shipped.\n`
      + (o.courier ? `Courier: ${o.courier}\n` : "")
      + (o.tracking_id ? `Tracking: ${o.tracking_id}\n` : "")
      + `\n— Aswin\nhttps://3d-prints.aswincloud.com\n`,
  },
  delivered: {
    subject: (o) => `Delivered — ${o.receipt}`,
    html: (env, o) => orderDeliveredEmail(env, o),
    text: (o) => `Your order ${o.receipt} has been delivered.\n`
      + `\nIf anything is not right, just reply to this email.\n\n— Aswin\n`
      + `https://3d-prints.aswincloud.com\n`,
  },
};

export async function updateOrder(env, id, body, ctx = null) {
  // SELECT * because the shipped email needs the customer's name, email and
  // address, and listing them here would mean editing this query every time the
  // template wants another field.
  const order = await env.DB.prepare(
    `SELECT * FROM orders WHERE id = ?`
  ).bind(id).first();
  if (!order) return bad("Order not found.", 404);

  const sets = [];
  const args = [];
  // The stage just ENTERED, or null. Null when the status did not change, which
  // is what stops a re-save from re-notifying.
  let entered = null;

  if ("status" in body) {
    const next = clip(body.status, 20);
    if (!ORDER_STATUSES.includes(next)) return bad("Unknown status.");
    if (next === "paid") {
      return bad("An order is marked paid by Razorpay's webhook, not by hand.", 409);
    }
    if (next === "refunded") {
      return bad("Use the refund action so the money actually moves.", 409);
    }
    const allowed = ALLOWED_TRANSITIONS[order.status] || [];
    if (next !== order.status && !allowed.includes(next)) {
      return bad(`Cannot go from "${order.status}" to "${next}".`, 409);
    }
    sets.push("status = ?"); args.push(next);

    // Only on the TRANSITION. Re-saving an order that is already shipped — to
    // correct a typo'd tracking number, say — must not stamp a new time over the
    // real one, and must not send a second "your order has shipped" email.
    if (next !== order.status) {
      entered = next;
      const stamp = STAGE_STAMP[next];
      if (stamp) { sets.push(`${stamp} = ?`); args.push(now()); }
    }
  }

  if ("notes" in body) { sets.push("notes = ?"); args.push(clip(body.notes, MAXLEN.note)); }

  // Both optional, and both stored rather than only emailed: the tracking number
  // is what a customer asks about a week later, and it has to be findable then.
  if ("courier" in body) { sets.push("courier = ?"); args.push(clip(body.courier, MAXLEN.courier) || null); }
  if ("tracking_id" in body) { sets.push("tracking_id = ?"); args.push(clip(body.tracking_id, MAXLEN.tracking) || null); }

  if (!sets.length) return bad("Nothing to update.");

  args.push(id);
  await env.DB.prepare(`UPDATE orders SET ${sets.join(", ")} WHERE id = ?`).bind(...args).run();

  const row = await env.DB.prepare(
    `SELECT id, receipt, status, notes, paid_at, production_at, ready_at,
            shipped_at, delivered_at, courier, tracking_id FROM orders WHERE id = ?`
  ).bind(id).first();

  // Tell the customer. The confirmation email promises "I'll email you again when
  // it ships" — until now nothing kept that promise.
  //
  // Sent through waitUntil so a slow or failing Resend call does not hold up the
  // dashboard, and a failure is logged rather than surfaced: the order IS shipped
  // either way, and an error toast would suggest the status change did not stick.
  const mail = entered ? STAGE_EMAIL[entered] : null;
  if (mail && env.RESEND_API_KEY) {
    const merged = { ...order, ...row };
    const send = sendEmail(env, {
      to: merged.cust_email,
      replyTo: env.OWNER_EMAIL || "aswin@aswincloud.com",
      subject: mail.subject(merged),
      html: mail.html(env, merged),
      text: mail.text(merged),
    }).then((r) => {
      if (!r.ok) console.error(`${entered} email failed`, merged.receipt, r.status, r.error);
    });
    if (ctx?.waitUntil) ctx.waitUntil(send); else await send;
  }

  // `emailed` drives the dashboard's toast, so it must reflect whether a mail
  // actually went — entering `ready` changes the order and sends nothing.
  return json({ ok: true, order: row, emailed: Boolean(mail && env.RESEND_API_KEY) });
}

// A direct tracking link where the courier is one we can recognise, otherwise
// nothing — the email falls back to the receipt button.
//
// Deliberately a small allowlist rather than a guess at a url pattern: a wrong
// link is worse than none, because the customer clicks it, gets an error page,
// and concludes the parcel is lost. Matched loosely so "Blue Dart", "bluedart"
// and "BLUEDART courier" all resolve.
function trackingUrlFor(courier, tracking) {
  if (!courier || !tracking) return "";
  const key = String(courier).toLowerCase().replace(/[^a-z]/g, "");
  const id = encodeURIComponent(String(tracking).trim());
  if (key.includes("bluedart")) return `https://www.bluedart.com/tracking?trackingNo=${id}`;
  if (key.includes("delhivery")) return `https://www.delhivery.com/track/package/${id}`;
  if (key.includes("dtdc")) return `https://www.dtdc.in/tracking.asp?strCnno=${id}`;
  if (key.includes("indiapost") || key.includes("speedpost")) {
    return `https://www.indiapost.gov.in/_layouts/15/DOP.Portal.Tracking/TrackConsignment.aspx`;
  }
  if (key.includes("xpressbees")) return `https://www.xpressbees.com/shipment/tracking?awb=${id}`;
  if (key.includes("ecom")) return `https://ecomexpress.in/tracking/?awb_field=${id}`;
  return "";
}

// ── refunds ───────────────────────────────────────────────────────
// Real money. Guarded accordingly: only a paid/shipped order, only up to what
// was actually collected, and the local row is only updated after Razorpay
// confirms — so a failed refund never shows as refunded.
export async function refundOrder(env, id, body) {
  if (!paymentsConfigured(env)) return bad("Razorpay isn't configured.", 503);

  const order = await env.DB.prepare(
    `SELECT id, receipt, status, total_paise, rzp_payment_id FROM orders WHERE id = ?`
  ).bind(id).first();
  if (!order) return bad("Order not found.", 404);

  if (!order.rzp_payment_id) {
    return bad("This order has no payment to refund.", 409);
  }
  if (!REFUNDABLE.includes(order.status)) {
    return bad(`Cannot refund an order with status "${order.status}".`, 409);
  }

  // Omit the amount for a full refund; otherwise partial.
  const requested = parsePaise(body?.amount_paise);
  if (body?.amount_paise !== undefined && requested === null) {
    return bad("Refund amount must be a whole number of paise.");
  }
  if (requested !== null && requested < 100) {
    return bad("Refund must be at least ₹1.");
  }
  if (requested !== null && requested > order.total_paise) {
    return bad(`Cannot refund more than the ₹${(order.total_paise / 100).toFixed(2)} collected.`);
  }

  const partial = requested !== null && requested < order.total_paise;

  const r = await refundPayment(env, order.rzp_payment_id, partial ? requested : undefined);
  if (!r.ok) {
    console.error("refund failed", order.receipt, r.status, JSON.stringify(r.body || {}));
    const desc = r.body?.error?.description;
    return bad(desc ? `Razorpay refused the refund: ${desc}` : "The refund could not be processed.", 502);
  }

  // Only a FULL refund changes the order's status; a partial one is recorded in
  // the notes so the order stays fulfilable.
  if (partial) {
    const note = `Partial refund of ₹${(requested / 100).toFixed(2)} (${r.refund?.id || "no id"}).`;
    await env.DB.prepare(
      `UPDATE orders SET notes = TRIM(COALESCE(notes,'') || ' ' || ?) WHERE id = ?`
    ).bind(note, id).run();
  } else {
    await env.DB.prepare(`UPDATE orders SET status = 'refunded' WHERE id = ?`).bind(id).run();
  }

  return json({
    ok: true,
    partial,
    refund_id: r.refund?.id || null,
    amount_paise: partial ? requested : order.total_paise,
  });
}

// ── dashboard summary ─────────────────────────────────────────────
export async function stats(env) {
  // Every stage from paid onwards is money that has arrived. This counted only
  // 'paid' and 'shipped', so the moment an order was marked "in production" it
  // fell out of the revenue figure and came back when it shipped — the number on
  // the dashboard went DOWN as work progressed.
  const paid = await env.DB.prepare(
    `SELECT COUNT(*) AS orders, COALESCE(SUM(total_paise),0) AS revenue
       FROM orders WHERE status IN ('paid','in_production','ready','shipped','delivered')`
  ).first();
  const pending = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM orders WHERE status = 'pending'`
  ).first();
  const products = await env.DB.prepare(
    `SELECT COUNT(*) AS total, COALESCE(SUM(visible),0) AS visible FROM products`
  ).first();
  return json({
    paid_orders: paid?.orders || 0,
    revenue_paise: paid?.revenue || 0,
    pending_orders: pending?.n || 0,
    products_total: products?.total || 0,
    products_visible: products?.visible || 0,
  });
}
